apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-transformer
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: influx-transformer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Values.service.protocol | lower }}
              protocol: {{ .Values.service.protocol }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: OTLP_URL
              valueFrom:
                secretKeyRef:
                  name: otlp-url-secret
                  key: OTLP_URL
          securityContext:
            runAsUser: 1001
            capabilities:
              drop:
                - NET_RAW
