apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-otel-http
spec:
  selector:
    app: alloy-overlay-otlp
  ports:
    - protocol: TCP
      port: 4318
      targetPort: 4318