apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-otel-grpc
spec:
  selector:
    app: alloy-overlay-otlp
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317