apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-kube-metrics-cluster
  labels:
    app: {{ .Values.fullnameOverride }}-kube-metrics
spec:
  type: ClusterIP
  selector:
    app: alloy-overlay-kube-metrics
  ports:
    - name: http
      port: 12346
      targetPort: 12346
      protocol: "TCP"
