apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride }}-kube-metrics
  labels:
    app: {{ .Values.fullnameOverride }}-kube-metrics
    app.kubernetes.io/name: alloy
spec:
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride }}-kube-metrics
  replicas: {{ .Values.kubeMetrics.controller.replicas }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Values.fullnameOverride }}-kube-metrics
    spec:
      containers:
      - args:
        - run
        - /etc/alloy/{{ .Values.kubeMetrics.configMap.key }}
        - --storage.path=/tmp/alloy
        - --server.http.listen-addr=0.0.0.0:12346
        - --server.http.ui-path-prefix=/
        - --stability.level=generally-available
        - --cluster.enabled=true
        - --cluster.join-addresses={{ .Values.fullnameOverride }}-kube-metrics-cluster
        - --disable-reporting
        env:
        - name: ALLOY_DEPLOY_MODE
          value: helm
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: HOSTIP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: KUBELET_SERVICE_PORT
          value: "10250"
        envFrom:
        {{- toYaml .Values.kubeMetrics.envFrom | nindent 8 }}
        image: "{{ .Values.alloy.global.image.registry }}/{{ .Values.alloy.image.repository }}:{{ .Values.alloy.image.tag }}"
        imagePullPolicy: "Always"
        name: alloy
        volumeMounts:
        - mountPath: /etc/alloy
          name: config
        ports:
        - containerPort: 12346
          name: http-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 12346
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          {{ toYaml .Values.kubeMetrics.resources | nindent 10 }}
      - args:
        - --volume-dir=/etc/alloy
        - --webhook-url=http://localhost:12346/-/reload
        image: "{{ .Values.alloy.global.image.registry }}/{{ .Values.alloy.configReloader.image.repository }}:{{ .Values.alloy.configReloader.image.tag }}"
        imagePullPolicy: "Always"
        name: config-reloader
        resources:
          requests:
            cpu: 1m
            memory: 5Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alloy
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: {{ .Values.fullnameOverride }}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Values.fullnameOverride }}-kube-metrics
        name: config