apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-otlp-cluster
  labels:
    app: {{ .Values.fullnameOverride }}-otlp
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.fullnameOverride }}-otlp
  ports:
    - name: http
      port: 12347
      targetPort: 12347
      protocol: "TCP"
