{
 "title": "DIM IAM Services",
 "tags": [
  "DIM",
  "IAM"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Region", "label": "Region", "query": "prometheus" },
   { "name": "Stack", "label": "Stack", "query": { "query": "label_values(stack_id)" } },
   { "name": "Environment", "label": "Environment", "query": { "query": "label_values(env_id)" } },
   { "name": "Service", "label": "Service", "query": "did, pid, idp, trt, ums" },
   { "name": "SubService", "label": "SubService", "query": "oam, odj, odj-ilb, oam-ilb" }
  ]
 },
 "panels": [
  { "title": "Infra - VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance) (irate(node_cpu_seconds_total{instance=~\".*$Stack-$Environment-$Service[0-9]*-app.*\", mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * (1 - avg by(instance) (irate(node_cpu_seconds_total{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService-[0-9].*\", mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * (1 - avg by(instance) (irate(node_cpu_seconds_total{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService[0-9].*\", mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-app.*\"} + node_memory_Buffers_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-app.*\"} + node_memory_Cached_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-app.*\"}) / node_memory_MemTotal_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-app.*\"}))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService-[0-9].*\"} + node_memory_Buffers_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService-[0-9].*\"} + node_memory_Cached_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService-[0-9].*\"}) / node_memory_MemTotal_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService-[0-9].*\"}))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService[0-9].*\"} + node_memory_Buffers_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService[0-9].*\"} + node_memory_Cached_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService[0-9].*\"}) / node_memory_MemTotal_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService[0-9].*\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-app.*\", filesystem!~\"tmpfs|fuse.lxcfs|squashfs\", mountpoint=~\"/|/data\"} / node_filesystem_size_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-app.*\", filesystem!~\"tmpfs|fuse.lxcfs|squashfs\", mountpoint=~\"/|/data\"}))",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    },
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService-[0-9].*\", filesystem!~\"tmpfs|fuse.lxcfs|squashfs\", mountpoint=~\"/|/data\"} / node_filesystem_size_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService-[0-9].*\", filesystem!~\"tmpfs|fuse.lxcfs|squashfs\", mountpoint=~\"/|/data\"}))",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    },
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService[0-9].*\", filesystem!~\"tmpfs|fuse.lxcfs|squashfs\", mountpoint=~\"/|/data\"} / node_filesystem_size_bytes{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService[0-9].*\", filesystem!~\"tmpfs|fuse.lxcfs|squashfs\", mountpoint=~\"/|/data\"}))",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\".*$Stack-$Environment-$Service[0-9]*-app.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "time() - node_boot_time_seconds{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService-[0-9].*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "time() - node_boot_time_seconds{instance=~\".*$Stack-$Environment-$Service[0-9]*-$SubService[0-9].*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}