name: Deploy Dataflow - Auto (Develop)
on:
  workflow_dispatch:
    inputs:
      terraform_workspace_select:
        description: "Select the Terraform workspace to deploy"
        required: false
        type: choice
        default: default
        options:
          - default
          - dev
  workflow_run:
    workflows: [Build Dataflow Image ]
    types: [completed]
    branches: [develop]
    
jobs:
  pre-requisite:
    runs-on: ubuntu-24.04
    steps:
      - name: on-failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('The triggering workflow failed')              
  trigger-deployment-dataflow-workflow-dev-s01:
    needs: pre-requisite
    uses: ./.github/workflows/deployment-dataflow.yml
    secrets: inherit # pass all secrets to the called workflow
    with:
      terraform_operation: 'apply'
      etlProject: 'd-ulti-pf-use4-dev-s01-fbe8'
      dataflow_image_version: 'latest'
      branch: 'develop'
      terraform_workspace_select: ${{ inputs.terraform_workspace_select || 'dev'}}
