name: Utility - FF Check
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
jobs:
  check-fast-forward:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checking if fast forwarding is possible
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: false
          comment: always
