apiVersion: v1
kind: Secret
metadata:
  labels:
    env_type: {{ .Values.env_type }}
    substream_id: {{ .Values.substream_id }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
stringData:
  IST_INTEGRATION_CONFIG_CMD_MONGODB_URI: {{ .Values.secrets.IST_INTEGRATION_CONFIG_CMD_MONGODB_URI     | quote }}
  IST_INTEGRATION_SCHEDULER_MONGODB_URI: {{ .Values.secrets.IST_INTEGRATION_SCHEDULER_MONGODB_URI     | quote }}
  IST_VENDOR_FILE_TYPE_CONFIG_CMD_MONGODB_URI: {{ .Values.secrets.IST_VENDOR_FILE_TYPE_CONFIG_CMD_MONGODB_URI     | quote }}
  MULE_VAULT_CERT: {{ .Values.secrets.MULE_VAULT_CERT | quote }}
  MULE_VAULT_KEY: {{ .Values.secrets.MULE_VAULT_KEY | quote }}
  VAULT_CERT: {{ .Values.secrets.VAULT_CERT | quote }}
  VAULT_KEY: {{ .Values.secrets.VAULT_KEY | quote }}
type: opaque
