apiVersion: v1
kind: Service
metadata:
    # prometheus.io/path: /_manage/metrics
    # prometheus.io/port: '8080'
    # prometheus.io/scrape: 'true'
    # quark.ukg.int/quark-phoenix-deployment-worker-version: 0.7.5
  labels:
    app.kubernetes.io/instance: '{{ .Values.name }}'
    # app.kubernetes.io/managed-by: quark-phoenix
    app.kubernetes.io/name: '{{ .Values.name }}'
    env_type: {{ .Values.env_type }}
    ist.ulti.io/vault: 'true'
    ist.ulti.io/zuul-integration-platform-gateway: 'true'
    # logging_index: ist
    substream_id: {{ .Values.substream_id }}
  name: '{{ .Values.name }}'
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: '{{ .Values.name }}'
    app.kubernetes.io/name: '{{ .Values.name }}'
